### ISSUE TITLE
multiple prompt doesn't work properly

### ISSUE THREAD

**Issue by dmeijboom** [Papierkorb/fancyline#4]
Hi! So it looks like multi line prompts aren't supported since when I use it the line is displayed nth characters after the number of characters on the first line.

I can probably take a look at it but terminal IO still looks like magic to me. Thanks!

Crystal version: 0.30.1

**Comment by dmeijboom** [comment]
Or actually this does work.. At least when you use ``\r\n``. Sorry! Great library btw ;)

**Comment by Papierkorb** [comment]
Hi!
Indeed you have to use `\r\n` even though `\n` suffices "everywhere else".  The reason is that the input prompt puts the terminal into direct mode (I think it was called), so characters that are sent to it are simply written/"executed" without further processing.  So to get to a new line, you do Carriage-Return `\r` to move the cursor to the beginning of the line, and follow it up by a Line-Feed `\n` to move the cursor to the next line.  You could practically also swap these two.
